"""intensity light

Revision ID: 1683cd0bc6d1
Revises: d3c5357910dd
Create Date: 2018-08-12 11:25:52.282123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1683cd0bc6d1'
down_revision = 'd3c5357910dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('current__state', sa.Column('light_intensity', sa.Integer(), nullable=True))
    op.add_column('user__state', sa.Column('light_intensity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__state', 'light_intensity')
    op.drop_column('current__state', 'light_intensity')
    # ### end Alembic commands ###
