"""cambio esquemas totales

Revision ID: 93ad7ef890e7
Revises: 1683cd0bc6d1
Create Date: 2018-10-28 10:32:24.443708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ad7ef890e7'
down_revision = '1683cd0bc6d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current__light__state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('light_state', sa.Boolean(), nullable=True),
    sa.Column('light_intensity', sa.Integer(), nullable=True),
    sa.Column('str_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current__light__state_timestamp'), 'current__light__state', ['timestamp'], unique=False)
    op.create_index(op.f('ix_current__light__state_user'), 'current__light__state', ['user'], unique=False)
    op.create_table('current__temperature__state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('temp_state', sa.Boolean(), nullable=True),
    sa.Column('temp_set_point', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current__temperature__state_timestamp'), 'current__temperature__state', ['timestamp'], unique=False)
    op.create_index(op.f('ix_current__temperature__state_user'), 'current__temperature__state', ['user'], unique=False)
    op.create_table('scheduled_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('str_id', sa.String(length=64), nullable=True),
    sa.Column('pid', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_events_pid'), 'scheduled_events', ['pid'], unique=True)
    op.create_index(op.f('ix_scheduled_events_timestamp'), 'scheduled_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_scheduled_events_user'), 'scheduled_events', ['user'], unique=False)
    op.create_table('user__light__state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('light_state', sa.Boolean(), nullable=True),
    sa.Column('light_intensity', sa.Integer(), nullable=True),
    sa.Column('str_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user__light__state_timestamp'), 'user__light__state', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user__light__state_user'), 'user__light__state', ['user'], unique=False)
    op.create_table('user__temperature__state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('temp_state', sa.Boolean(), nullable=True),
    sa.Column('temp_set_point', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user__temperature__state_timestamp'), 'user__temperature__state', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user__temperature__state_user'), 'user__temperature__state', ['user'], unique=False)
    op.drop_index('ix_user__state_timestamp', table_name='user__state')
    op.drop_table('user__state')
    op.drop_table('current__state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current__state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('light_state', sa.BOOLEAN(), nullable=True),
    sa.Column('temp_state', sa.FLOAT(), nullable=True),
    sa.Column('light_intensity', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('light_state IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__state',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('light_state', sa.BOOLEAN(), nullable=True),
    sa.Column('temp_state', sa.FLOAT(), nullable=True),
    sa.Column('light_intensity', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('light_state IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user__state_timestamp', 'user__state', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_user__temperature__state_user'), table_name='user__temperature__state')
    op.drop_index(op.f('ix_user__temperature__state_timestamp'), table_name='user__temperature__state')
    op.drop_table('user__temperature__state')
    op.drop_index(op.f('ix_user__light__state_user'), table_name='user__light__state')
    op.drop_index(op.f('ix_user__light__state_timestamp'), table_name='user__light__state')
    op.drop_table('user__light__state')
    op.drop_index(op.f('ix_scheduled_events_user'), table_name='scheduled_events')
    op.drop_index(op.f('ix_scheduled_events_timestamp'), table_name='scheduled_events')
    op.drop_index(op.f('ix_scheduled_events_pid'), table_name='scheduled_events')
    op.drop_table('scheduled_events')
    op.drop_index(op.f('ix_current__temperature__state_user'), table_name='current__temperature__state')
    op.drop_index(op.f('ix_current__temperature__state_timestamp'), table_name='current__temperature__state')
    op.drop_table('current__temperature__state')
    op.drop_index(op.f('ix_current__light__state_user'), table_name='current__light__state')
    op.drop_index(op.f('ix_current__light__state_timestamp'), table_name='current__light__state')
    op.drop_table('current__light__state')
    # ### end Alembic commands ###
